[package]
name = "magma-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [
    "cdylib",
    # "rlib"
]

[dependencies]
cosmwasm-std = { version = "1.0.0", features = [] }
serde = { version = "1.0.202", default-features = false, features = ["derive"] }
cw-storage-plus = "1.0.0"
thiserror = "1"

# schemars = "0.8.20"
cosmwasm-schema = "1.0.0"
osmosis-std = "0.25.0"
# osmosis-std-derive = "0.20.1"
cw-utils = "2.0.0"

[dev-dependencies]
cw-multi-test = "2.0.1"

