[alias]
wasm = "build --target wasm32-unknown-unknown --release --lib"
w = "build --target wasm32-unknown-unknown --release --lib"
wasm-debug = "build --target wasm32-unknown-unknown --lib"
wd = "build --target wasm32-unknown-unknown"

